module.exports = {
    INSTAGRAM_CLIENT_ID: process.env.INSTAGRAM_CLIENT_ID,
    INSTAGRAM_CLIENT_SECRET: process.env.INSTAGRAM_CLIENT_SECRET,
    REDIRECT_URI: process.env.REDIRECT_URI,
    JWT_SECRET: process.env.JWT_SECRET
  };